/**
 * Structures for handshake messages and session handling.
 *
 * @author Elmo Moilanen
 */

#pragma once

#include <cstdint>
#include <optional>
#include "config.hpp"

namespace handshake
{
    #pragma pack(push, 1)

    struct ClientHello
    {
        uint8_t client_nonce[handshake::config::NONCE_SIZE]; // Random nonce generated by the client
        uint8_t supported_algorithms;                        // Bitfield of algorithms supported by the client
    };

    struct ServerHello
    {
        uint8_t chosen_algorithm;                                                    // Algorithm chosen from bitfield by the server
        uint8_t server_nonce[handshake::config::NONCE_SIZE];                         // Random nonce generated by the server
        uint8_t server_x25519_public_key[handshake::config::X25519_PUBLIC_KEY_SIZE]; // Public x25519 key generated by the server
        uint8_t server_kyber_public_key[handshake::config::KYBER_PUBLIC_KEY_SIZE];   // Public Kyber key generated by the server
    };

    struct ClientKeyShare
    {
        uint8_t x25519_public_key[handshake::config::X25519_PUBLIC_KEY_SIZE];            // Public x25519 key generated by the client
        uint8_t kyber_ciphertext_encapsulated[handshake::config::KYBER_CIPHERTEXT_SIZE]; // Kyber ciphertext generated by the client
    };

    struct FinishedMessage
    {
            
    };

    #pragma pack(pop)

    struct SessionKeys
    {
        uint8_t session_key[handshake::config::SESSION_KEY_SIZE]; // Shared session key
        uint8_t session_nonce[handshake::config::NONCE_SIZE];     // Nonce for the session key
    };

    std::optional<SessionKeys> client_handshake(int socket, uint8_t algorithm = handshake::config::HYBRID);
    std::optional<SessionKeys> server_handshake(int socket);
}
